### ISSUE TITLE
consider adding to the BN plugin manager?

### ISSUE THREAD

**Issue by psifertex** [junron/auto-enum#3]
Just need to [create a release](https://docs.binary.ninja/dev/plugins.html#submitting-to-the-plugin-manager) and let us know and we'll add it and automatically track new releases for update in the plugin manager. The only issue is that the subdirectory would need to be loaded as a folder, not a single file so just moving logic into a subfolder with an `__init__.py` would be required.

You can see how [lighthouse](https://github.com/gaasedelen/lighthouse/tree/master/binjastub) does it and then we just specify the subfolder of the repo in the [BN plugin manager listing](https://github.com/Vector35/community-plugins/blob/master/listing.json#L313-L315).

Thanks for adding BN support either way!

**Comment by junron** [comment]
Sounds great! I'll sort it out when I have time

**Comment by psifertex** [comment]
Sounds good! Let me know if you have any trouble or questions.

**Comment by junron** [comment]
Hopefully this works:

https://github.com/junron/auto-enum/releases/tag/v0.1.0

**Comment by psifertex** [comment]
Replied on the other issue but the TL;DR is that you need to have the tag match the version in plugin.json. So "0.1.0" instead of "v0.1.0"

**Comment by junron** [comment]
I have updated the release to "0.1.0": https://github.com/junron/auto-enum/releases/tag/0.1.0

**Comment by psifertex** [comment]
Thanks! Added. Should be live in the plugin manager.
