### ISSUE TITLE
Can you update Windows gen py files

### ISSUE THREAD

**Issue by HongThatCong** [junron/auto-enum#5]
I share .md files with Alexander Hanel's msdocsviewer plugin [link](https://github.com/alexander-hanel/msdocsviewer)
It includes sdk-api and windows-driver-docs-ddi
I made some minor modifications to your gen\windows\*.py.

Still generates json files, but the dict format in those json files is still the old data from your previous version.

No field args, varargs...
So the plugin will raise an exception in the following line of code in enumlib\\\_\_init\_\_.py
```python
func = Function(self, data["name"], [Argument(arg) for arg in data["args"]], data["varargs"])
```
Please update gen\windows\*.py

Thank you very much

**Comment by junron** [comment]
Added in https://github.com/junron/auto-enum/commit/c1595f8f74ac24592003557a11ff9821a9dc2e61
