### ISSUE TITLE
bug with some struct or class

### ISSUE THREAD

**Issue by robyousugar** [junron/auto-enum#6]
some bug here~,some struct or class.
![bug](https://github.com/user-attachments/assets/38ccfb73-7ae8-4758-965f-13693f212155)

**Comment by robyousugar** [comment]
IDA 9.0

**Comment by junron** [comment]
What function is involved here? Is it possible for you to send over a minimal binary that reproduces this behavior?

**Comment by robyousugar** [comment]
sorry,i checked this bug is other plugin.
